### ISSUE TITLE
AvatarWebKit api token

### ISSUE THREAD

**Issue by kruzel** [Hallway-Inc/AvatarWebKit#8]
Hi,
I'm unable to get api token from your website, error says user already exist.
How can I get api token if I already register thru the windows app?
Thanks,
Ofer Kruzel
M: +972 (54) 4516627

**Comment by talgki** [comment]
Same problem, any clues?

**Comment by noti56** [comment]
Cant Sign up to get the token.

**Comment by alexbeattie42** [comment]
Unfortunately, token access has been suspended.
